---
title: "data cleaning 4 df4"
output: html_notebook
---


```{r}
#Correct the Household Size columnn names after importing to R
colnames(df4)[11]="0-15"
colnames(df4)[12]="16-30"
colnames(df4)[13]="31-45"
colnames(df4)[14]="46-60"
colnames(df4)[15]="61-up"
```


```{r}
#Convert zeros to NA for missing data in preparation for RF; df4 is the combined survey with the serology data after data cleaning 3
df4[df4==0] <- NA
```

```{r}
#summarize data to see how many missing values are in each 
#column/feature
summary(df4)
```


```{r}
#Import missForest to impute missing values for mixed variable/
#feature types
library(missForest)
```
```{r}
#Impute missing values using missForest; df4missing updated df4 frame
df4missing<-missForest(df4)
```


```{r}
#Ensure data was imputed with missForest
class(df4missing)
```

```{r}
#Call the new data frame (impdf4) with the new imputed values
impdf4<-df4missing$ximp
impdf4
```

```{r}
#summarize impdf2 to show that missing values have been replaced
#with missForest imputation
summary(impdf4)
```
```{r}
write.csv(impdf4, "C:/Users/rothg/Desktop/Dissertation Proposal/impdf4.csv", row.names=TRUE)
```
